server:
  port: 80

spring:
  application:
    name: upload-file
  data:
    mongodb:
      host: 172.17.0.2
      port: 27017
      database: demo
      username: admin
      password: admin
      authentication-database: admin

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html


